set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

find_program(ARM_NONE_EABI_GCC
    NAMES arm-none-eabi-gcc
    HINTS ${ARM_GNU_TOOLCHAIN_HINT_DIRS}
    REQUIRED
)

find_program(ARM_NONE_EABI_OBJCOPY
    NAMES arm-none-eabi-objcopy
    HINTS ${ARM_GNU_TOOLCHAIN_HINT_DIRS}
    REQUIRED
)

find_program(ARM_NONE_EABI_SIZE
    NAMES arm-none-eabi-size
    HINTS ${ARM_GNU_TOOLCHAIN_HINT_DIRS}
    REQUIRED
)

set(CMAKE_C_COMPILER ${ARM_NONE_EABI_GCC})
set(CMAKE_ASM_COMPILER ${ARM_NONE_EABI_GCC})
set(CMAKE_OBJCOPY ${ARM_NONE_EABI_OBJCOPY} CACHE INTERNAL "")
set(CMAKE_SIZE ${ARM_NONE_EABI_SIZE} CACHE INTERNAL "")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
